# Generated by Django 6.0.4 on 2026-04-29 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя автора')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Фото')),
                ('birth_year', models.IntegerField(blank=True, null=True, verbose_name='Год рождения')),
                ('death_year', models.IntegerField(blank=True, null=True, verbose_name='Год смерти')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='Биография')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
            ],
            options={
                'verbose_name': 'автор',
                'verbose_name_plural': 'Авторы',
            },
        ),
    ]
