# Generated by Django 6.0.4 on 2026-05-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.URLField(blank=True, null=True, verbose_name='Фото'),
        ),
    ]
