# Generated by Django 6.0.4 on 2026-05-03 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feedbback',
            new_name='Feedback',
        ),
    ]
