# Generated by Django 6.0.4 on 2026-04-29 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Слаг')),
                ('preview', models.TextField(verbose_name='Превью')),
                ('text', models.TextField(verbose_name='Текст')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poems', to='authors.author', verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'стихотворение',
                'verbose_name_plural': 'Стихотворения',
            },
        ),
    ]
